### ISSUE TITLE
instantseal password empty

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity-deploy#58]
thorough cleaning:
```
docker-compose down -v
docker rm $(docker ps -a -q); docker rmi $(docker images -q)
sudo rm -rf data/ deployment/ docker-compose.yml
sudo ./clean.sh 
```

there is a password created:
```
./parity-deploy.sh --config dev --name instantseal
cat  deployment/is_authority/password 
```
results in
```
s4LKh0oCw4jH1g1n
```

but then something's wrong:
```
docker-compose up

./deploy.py 
...
Traceback (most recent call last):
  File "./deploy.py", line 136, in <module>
    deployTheContract(contract_source_file=CONTRACT_SOURCE)
  File "./deploy.py", line 105, in deployTheContract
    print ("unlock: ", unlockAccount())
  File "/home/akrueger/Documents/Code/gitlab/electronDLT/chainhammer/clienttools.py", line 94, in unlockAccount
    duration=duration)
  File "/home/akrueger/Documents/Code/envs/py3eth/lib/python3.5/site-packages/web3/personal.py", line 43, in unlockAccount
    [account, passphrase, duration],
  File "/home/akrueger/Documents/Code/envs/py3eth/lib/python3.5/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])

ValueError: {'code': -32023, 'data': 'InvalidPassword', 'message': 'Unable to unlock the account.'}
```

found it out like this

```
geth attach http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Parity//v1.11.10-stable-31720e6-20180830/x86_64-linux-gnu/rustc1.28.0
coinbase: 0x00a329c0648769a73afac7f9381e08fb43dbea72
at block: 0 (Thu, 01 Jan 1970 01:00:00 BST)
 modules: eth:1.0 net:1.0 parity:1.0 parity_accounts:1.0 parity_set:1.0 personal:1.0 rpc:1.0 signer:1.0 traces:1.0 web3:1.0

> personal.unlockAccount(eth.accounts[0])
Unlock account 0x00a329c0648769a73afac7f9381e08fb43dbea72
Passphrase: 
true
```

instead of "`s4LKh0oCw4jH1g1n`", the password is ""

**Comment by drandreaskrueger** [comment]
also

```
./parity-deploy.sh --config dev --name instantseal
```

but then the chain is instead called `developmentchain`:

```
nodeName: Parity, nodeType: Parity, consensus: ???, network: 17, chainName: developmentchain, chainId: 17
```
see https://gitlab.com/electronDLT/chainhammer/blob/master/parity.md#run-8-instantseal

**Comment by ddorgan** [comment]
@drandreaskrueger Yes with the --dev chain the account password will be blank ... this is expected.

**Comment by drandreaskrueger** [comment]
then better don't generate an invalid password, no?
